### PR TITLE
Add a retile() function.

### PR DESCRIPTION
**Pull request by mavant**

### CODE REVIEW

**Comment by csaunders** [comment]
Code looks good. I'd just love to see more of a justification and an example of where you'd use it.

**Comment by mavant** [comment]
Oh, sorry - there was an explanation in the commit message that didn't end
up on the PR. I'm using this as a stopgap measure until mjolnir gets the
ability to listen to window manager events. Have a keybinding that just
does this is a bit faster than hitting mash+c three times whenever I open a
new window.

**Comment by csaunders** [comment]
coolbeans

**Comment by nathankot** [comment]
@mavant nice :+1: side note, I've been using `tiling.promote()` to achieve the same thing, but there are definitely cases where this will prove better

**Pull request merged**
